default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", nil) %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", nil) %>_development
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", nil) %>_test
  url: <%= ENV["DATABASE_URL"] %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: jet_fc_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: jet_fc_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: jet_fc_production_cable
    migrations_paths: db/cable_migrate
